variables:
  PROJECT_NAME: apolloconfigservice
  PROJECT_NAME2: apolloadminservice
  PROJECT_NAME3: apolloportal
  PROJECT_NAME4: apolloconfigpre
  IMAGE_NAME: registry.ebaolife.net/$PROJECT_NAME
  IMAGE_NAME2: registry.ebaolife.net/$PROJECT_NAME2
  IMAGE_NAME3: registry.ebaolife.net/$PROJECT_NAME3
  VERSION: 1.2.0

test-build:
  stage: build
  script:
    - bash scripts/build.sh
    - cp apollo-configservice/target/apollo-configservice-${VERSION}-github.zip apollo-configservice/src/main/docker
    - cd apollo-configservice/src/main/docker
    - docker build -t $IMAGE_NAME:$CI_BUILD_TAG . 
    - docker push $IMAGE_NAME:$CI_BUILD_TAG
    - cd -
    - cp apollo-adminservice/target/apollo-adminservice-${VERSION}-github.zip apollo-adminservice/src/main/docker
    - cd apollo-adminservice/src/main/docker
    - docker build -t $IMAGE_NAME2:$CI_BUILD_TAG . 
    - docker push $IMAGE_NAME2:$CI_BUILD_TAG
    - cd -
    - cp apollo-portal/target/apollo-portal-${VERSION}-github.zip apollo-portal/src/main/docker
    - cd apollo-portal/src/main/docker
    - docker build -t $IMAGE_NAME3:$CI_BUILD_TAG . 
    - docker push $IMAGE_NAME3:$CI_BUILD_TAG
  only:
    - /^.*-test$/
  tags:
    - test-docker

test-deploy:
  variables:
    INSTANCES: '1'
  stage: deploy
  script:
    - cd docker
    - sed -i "s/CI_COMMIT_TAG/$CI_COMMIT_TAG/g" k8s.yaml
    - kubectl apply -f k8s.yaml
#    - docker-compose -f docker-compose-test.yml pull
#    - docker-compose -f docker-compose-test.yml -p $PROJECT_NAME up -d
  only:
    - /^.*-test$/
  tags:
    - test-docker


pre-build:
  stage: build
  script:
    - bash scripts/build.sh
    - cp apollo-configservice/target/apollo-configservice-${VERSION}-github.zip apollo-configservice/src/main/docker
    - cd apollo-configservice/src/main/docker
    - docker build -t $IMAGE_NAME:$CI_BUILD_TAG . 
    - docker push $IMAGE_NAME:$CI_BUILD_TAG
    - cd -
    - cp apollo-adminservice/target/apollo-adminservice-${VERSION}-github.zip apollo-adminservice/src/main/docker
    - cd apollo-adminservice/src/main/docker
    - docker build -t $IMAGE_NAME2:$CI_BUILD_TAG . 
    - docker push $IMAGE_NAME2:$CI_BUILD_TAG
    - cd -
    - cp apollo-portal/target/apollo-portal-${VERSION}-github.zip apollo-portal/src/main/docker
    - cd apollo-portal/src/main/docker
    - docker build -t $IMAGE_NAME3:$CI_BUILD_TAG . 
    - docker push $IMAGE_NAME3:$CI_BUILD_TAG
  only:
    - /^.*-pre$/
  tags:
    - shell

pre-deploy:
  variables:
    INSTANCES: '1'
  stage: deploy
  script:
    - cd docker
    - sed -i "s/CI_COMMIT_TAG/$CI_COMMIT_TAG/g" k8s-pre.yaml
    - kubectl apply -f k8s-pre.yaml
#    - docker-compose -f docker-compose-pre.yml pull
#    - docker-compose -f docker-compose-pre.yml -p $PROJECT_NAME4 up -d
  only:
    - /^.*-pre$/
  tags:
    - test-docker 


prod-build:
  stage: build
  script:
    - bash scripts/build.sh
    - cp apollo-configservice/target/apollo-configservice-${VERSION}-github.zip apollo-configservice/src/main/docker
    - cd apollo-configservice/src/main/docker
    - docker build -t $IMAGE_NAME:$CI_BUILD_TAG . 
    - docker push $IMAGE_NAME:$CI_BUILD_TAG
    - cd -
    - cp apollo-adminservice/target/apollo-adminservice-${VERSION}-github.zip apollo-adminservice/src/main/docker
    - cd apollo-adminservice/src/main/docker
    - docker build -t $IMAGE_NAME2:$CI_BUILD_TAG . 
    - docker push $IMAGE_NAME2:$CI_BUILD_TAG
    - cd -
    - cp apollo-portal/target/apollo-portal-${VERSION}-github.zip apollo-portal/src/main/docker
    - cd apollo-portal/src/main/docker
    - docker build -t $IMAGE_NAME3:$CI_BUILD_TAG . 
    - docker push $IMAGE_NAME3:$CI_BUILD_TAG
  only:
    - /^.*-prod$/
  tags:
    - shell

prod-deploy:
  variables:
    INSTANCES: '1'
  stage: deploy
  script:
    - cd docker
    - sed -i "s/CI_COMMIT_TAG/$CI_COMMIT_TAG/g" k8s-prod.yaml
    - kubectl apply -f k8s-prod.yaml
#    - docker-compose pull
#    - docker-compose -p $PROJECT_NAME up -d
  only:
    - /^.*-prod$/
  tags:
    - prod-docker